# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 711e431409a8542254f3ceae2dfe822234292834f29c45d9679e14c67b18247395186f2e69fc59a55b5631feb0742b9c958b1b4978aebde50ce008e0738ba2f0

test:
  secret_key_base: 9d0b726e108fd8ab75d8429adc5a9064c6edca8f99378e3da8655c56570613f8718a86aade0abeadced89c55e3fd7bfd1ee833040b247eafdd2ae4039eacdb7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
