User.create!(name: "Felipa Schwarz", email: "felipaschwarz@gmail.com")
User.create!(name: "Vincent Schwarz", email: "vincent@fevini.com")
User.create!(name: "Nikos Schwarz", email: "nikos@fevini.com")
User.create!(name: "Mary Schwarz", email: "mkoliou@kolios.gr")
User.create!(name: "Marcus Schwarz", email: "mschwarz@pacific.com")